### ISSUE TITLE
RFE: choosing Service type

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#154]
When I'm using `kompose up` sometimes I need to change Service type.
Right now we generate services that are `ClusterIP`, but sometimes I want to have service exposed to outside of the cluster, than I have to manually change type and set it to `LoadBalancer`.

It would be nice to have a way to specify type of services.

### Proposal:
Use image label in docker-compose.yml to set type of services.
By default we would still create `ClusterIP` services, but when there is a specific label we would create `LoadBalancer`

example:
```yaml
version: "2"
services:
    backend:
        image: backend
        ports:
                - 3000:3000
    frontend:
        image: frontend
        ports:
                - 8080:8080
        environment:
                API_URL: http://backend:3000/api
        labels:
                kompose.service.public: True
```

we could use labels to specify Ingress/Route https://github.com/skippbox/kompose/issues/140

**Comment by dustymabe** [comment]
> Use image label in docker-compose.yml to set type of services.

+1. I wonder if we should make the labels kompose specific though. This would probably be a good thing for @pradeepto to weigh in on.

**Comment by ngtuna** [comment]
Otherwise, we can add `--external` flag ? I am also +1 for the kompose specific label.

**Comment by kadel** [comment]
I was also thinking about about doing this via cmd flag.
But downside of using flag is that you have to always remember to add that flag.

Benefit of doing it via label is that you do it only once. You edit file, commit it and than you can forget about it, and you have everything in one file.

Now when I'm thinking about it,  this could be also in preference file.
Than we can avoid modifying original docker-compose.yml file.

it can be just list of public service names
and for Ingress we can extend it to hostnames
```yaml
expose:
   - foo.bar.example.com=frontend # this will create Ingress/Route
   - frontend # this will create just LoadBalancer service
```

**Comment by surajssd** [comment]
Or how about the user mentions in preference file something like this:

```yaml
profiles:
  default:
    provider: kubernetes
    objects:
      - deployment
      - replicaset
      - ingress
current-context: default
```
