### ISSUE TITLE
Support for host:container:protocol

### ISSUE THREAD

**Issue by OguzPastirmaci** [kubernetes-incubator/kompose#335]
Marked as fixed in #158 but I still get the same error.

Definition in docker-compose file:
ports:
  - 127.0.0.1:15000:15000/tcp
  - 127.0.0.1:15001:15001/udp

FATA[0000] "agent" failed to load ports from compose file: invalid host port "127.0.0.1:15000:15000/tcp"

root@350035d7afc9:/compose# kompose -v
kompose version 0.1.2 (92ea047)

Let me know if I'm missing something.

**Comment by cdrage** [comment]
@OguzPastirmaci 

Yup. This looks like an error, we're testing against:

```
- "5000:5000/tcp"
```

but
```
- "127.0.0.1:5000:5000/tcp"
```

doesn't work and this:

```
test/fixtures/ports-with-proto  master ✗                                                                                                                                                                                                                                4h34m ⚑  
▶ kompose convert
FATA[0000] "web" failed to load ports from compose file: invalid host port "127.0.0.1:5000:5000/tcp" 
```

errors out.

**Comment by cdrage** [comment]
Hey @ngtuna @kadel 

Adding IP mapping via the port makes the *most* sense in regards to mapping to ClusterIP / LoadBalancerIP.

Would make things *awesome* in regards to scenarios of specifying certain IP addressing for each service.

Here's an example:

```
services:                                                                                                                                                                                                                                                                         
    web:                                                                                                                                                                                                                                                                          
      image: tuna/docker-counter23                                                                                                                                                                                                                                                
      ports:                                                                                                                                                                                                                                                                      
        - "127.0.0.1:5000:5000/tcp"                                                                                                                                                                                                                                               
      links:                                                                                                                                                                                                                                                                      
        - redis                                                                                                                                                                                                                                                                   
      networks:                                                                                                                                                                                                                                                                   
        - default  
```

Converts to:

```
    {                                                                                                                                                                                                                                                                             
      "kind": "Service",                                                                                                                                                                                                                                                          
      "apiVersion": "v1",                                                                                                                                                                                                                                                         
      "metadata": {                                                                                                                                                                                                                                                               
        "name": "web",                                                                                                                                                                                                                                                            
        "creationTimestamp": null,                                                                                                                                                                                                                                                
        "labels": {                                                                                                                                                                                                                                                               
          "service": "web"                                                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                         
      },                                                                                                                                                                                                                                                                          
      "spec": {                                                                                                                                                                                                                                                                   
        "ports": [                                                                                                                                                                                                                                                                
          {                                                                                                                                                                                                                                                                       
            "name": "5000",                                                                                                                                                                                                                                                       
            "protocol": "TCP",                                                                                                                                                                                                                                                    
            "port": 5000,                                                                                                                                                                                                                                                         
            "targetPort": 5000                                                                                                                                                                                                                                                    
          }                                                                                                                                                                                                                                                                       
        ],
       "clusterIP": "10.0.171.239",                                                                                                                                                                                                                                                                        
        "selector": {                                                                                                                                                                                                                                                             
          "service": "web"                                                                                                                                                                                                                                                        
        }                                                                                                                                                                                                                                                                         
      },                                                                                                                                                                                                                                                                          
      "status": {                                                                                                                                                                                                                                                                 
        "loadBalancer": {}                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                           
    },   
```

Does this make sense?

Or should we warn the user instead that it's not supported?
