### ISSUE TITLE
kompose up/down not creating/deleting POD object generated with convert

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#342]

**Comment by cdrage** [comment]
Hey @surajssd do you mind giving a test example? I'm trying to replicate this.

**Comment by kadel** [comment]
what this is about?

**Comment by kadel** [comment]
@surajssd 
Is this issue about this?

```yaml
version: "2"

services:
  foo:
    image: "busybox"
    restart: "on-failure"
    command: ["sleep", "30s"]
```

```
▶ kompose up       
WARN[0000] [foo] Service cannot be created because of missing port. 
We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 

FATA[0000] Error while deploying application: Deployment.extensions "foo" is invalid: spec.template.spec.restartPolicy: Unsupported value: "OnFailure": supported values: Always 
```
