### ISSUE TITLE
error should be displayed If controller object is specified  and `restart: on-failure` 

### ISSUE THREAD

**Issue by kadel** [kubernetes-incubator/kompose#354]
```yaml
version: "2"

services:
  foo:
    image: "busybox"
    restart: "on-failure"
    command: ["sleep", "30s"]
```

```
./kompose convert --deployment
INFO[0000] file "foo-pod.json" created
```

I would expect error or at least warning.
