### ISSUE TITLE
add support for mem_limit in kompose

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/kompose#364]
It would be great to have support for [mem_limit](https://docs.docker.com/compose/compose-file/#/cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-oomscoreadj-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir) which should translate to a pod's spec like -

```yaml
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      limits:
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    volumeMounts:
```
