### ISSUE TITLE
Unsupported root level networks key despite no networks

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#365]
The warning could be a bit more descriptive, but upon converting:
```
▶ cat script/test/fixtures/tty-true/docker-compose.yml 
version: "2"
services:
  client:
    image: registry.centos.org/centos/centos:7
    ports:
    - "1337"
    tty: true
```

It appears to output a warning in regards to a root level network, despite none being defined.

```
github.com/kubernetes-incubator/kompose  update-vendoring ✔                                                                                                                                                                                                                  2d
▶ kompose -f /home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/script/test/fixtures/tty-true/docker-compose.yml convert --stdout -j
WARN[0000] Unsupported root level networks key - ignoring
{                            
  "kind": "List",
  "apiVersion": "v1",
  "metadata": {},          
  "items": [      
    {                            
      "kind": "Service",                                       
      "apiVersion": "v1",     
      "metadata": {      
```
