### ISSUE TITLE
Converting docker-compose file on mac: `panic: runtime error`

### ISSUE THREAD

**Issue by jonathanstiansen** [kubernetes-incubator/kompose#379]
Hey guys, first post. If I need anymore info, just let me know. First time use, trying to follow your README but this is what I got. I used the `go get` method of installation

Details:
Mac OSX El Capitan 10.11.6

```
jono@JonosMacbookPro:~/p/portal3|⚡*?                                                                           
➤ echo $GOPATH
/Users/jono/golang
jono@JonosMacbookPro:~/p/portal3|⚡*?                                                                           
➤ echo $GOROOT
/usr/local/opt/go/libexec
jono@JonosMacbookPro:~/p/portal3|⚡*?                                                                           
# First I tried Go version 1.6.x and it had the same thing, this is run with 1.7
➤ go version
go version go1.7.4 darwin/amd64
jono@JonosMacbookPro:~/p/portal3⚡*?                                                                           
➤ kompose -f docker-compose.yml convert
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0xb454f0]

goroutine 1 [running]:
panic(0x1f0dd80, 0xc8200100d0)
        /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).handleVolumeConfig(0xc8200d0700)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:319 +0x430
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).load(0xc8200d0700, 0x7fff5fbffa73, 0x12, 0xc820282000, 0x3a5, 0x5a5, 0x0, 0x0)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:235 +0x649
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc8200d0700, 0x0, 0x0)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:112 +0x335
github.com/kubernetes-incubator/kompose/pkg/loader/compose.(*Compose).LoadFile(0x3512d68, 0xc8202732a0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/pkg/loader/compose/compose.go:262 +0x555
github.com/kubernetes-incubator/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc8202732a0, 0x1, 0x1, ...)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/pkg/app/app.go:195 +0x1d2
github.com/kubernetes-incubator/kompose/cmd.glob.func2(0x34e0960, 0xc8200f6460, 0x0, 0x2)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/cmd/convert.go:80 +0x27
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x34e0960, 0xc8200f6300, 0x2, 0x2, 0x0, 0x0)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:603 +0x896
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x34e0da0, 0x34e0960, 0x0, 0x0)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:689 +0x55c
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x34e0da0, 0x0, 0x0)
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:648 +0x2d
github.com/kubernetes-incubator/kompose/cmd.Execute()
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/cmd/root.go:86 +0x27
main.main()
        /Users/jono/golang/src/github.com/kubernetes-incubator/kompose/main.go:22 +0x14
```

My docker-compose file:

```
➤ cat docker-compose.yml
version: '2'
services:
  web:
    command: /sbin/my_init
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/home/app
      - ./certs/production/:/etc/ssl/certs:ro
      - ./certs/dhparam.pem:/etc/ssl/private/dhparam.pem:ro
      - ./certs/private/wildcard.com.key:/etc/ssl/private/wildcard.com.key:ro
      - ./staging.conf:/etc/nginx/sites-enabled/portal.conf
    env_file: ./config/environments/development.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - memcached
      - redis
      - mailcatcher
  db:
    image: sandbox-psql
    volumes:
      - data:/var/lib/postgresql/data
  memcached:
    image: memcached:1.4.28-alpine
  redis:
    image: redis:3.2-alpine
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
volumes:
  data:
```
