### ISSUE TITLE
error: Could not unmarshal '<nil>' to type <nil>

### ISSUE THREAD

**Issue by Hashfyre** [kubernetes-incubator/kompose#388]
Platform:
  os: OS X Yosemite - 10.10.5 (14F2109)
  kompose: version 0.1.2 (92ea047)
compose-file:
```
version: '2'
services:
  <project>:
    build:
      context: .
      args:
        GIT_TOKEN:
    image: <private-img>
    links:
      - db_live
    depends_on:
      - db_live
    ports:
      - 28090:80
    environment:
      DB_HOST: db_live
  db_live:
    image: mysql:5.6
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <passwd>
      MYSQL_DATABASE: <project>
      MYSQL_USER: <project>
      MYSQL_PASSWORD: <passwd>
```
Angular brackets are indicative of replacement text.

Command:
 - `kompose -f docker-compose.yml convert`

Error Output:
 - `ERRO[0000] Could not parse config for project <project> : Cannot unmarshal '<nil>' to type <nil> into a string value`
