### ISSUE TITLE
environment variables not being set in buildConfig

### ISSUE THREAD

**Issue by arcolife** [kubernetes-incubator/kompose#406]
relevant dockerfile snippet: https://github.com/arcolife/sarjitsu/blob/master/lib/datasource/Dockerfile#L26

https://github.com/arcolife/sarjitsu/blob/master/docker-compose.yml#L21
This is the environment variable, whose value I expect to be picked from the env file (based off of docker-composed env file) https://github.com/arcolife/sarjitsu/blob/master/.env file and set in the generated buildconfig file (per se: datasource-buildconfig.yaml), as illustrated below:

```yaml
...
  source:
    contextDir: lib/datasource
    git:
      ref: komposed
      uri: https://github.com/arcolife/sarjitsu.git
    type: Git
  strategy:
    dockerStrategy:
      env:
        - name: ES_PORT
          value: "9200"
    type: Docker
...
```

Currently no env variables are being set in the build config.
