### ISSUE TITLE
Cannot unmarshal float environment values.

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#410]
When passing in a float value through `env:` seems to fail:

Ex:
```
  environment:
    TEST: 4
    BAR: 0.3
    FOO: 0.3
```

```
ERRO Could not parse config for project foobar : Cannot unmarshal '0.3' of type float64 into a string value 
FATA Failed to load compose file: Cannot unmarshal '0.3' of type float64 into a string value 
```
