### ISSUE TITLE
Error to parse docker-compose v3 format

### ISSUE THREAD

**Issue by pivulic** [kubernetes-incubator/kompose#412]
## Problem
When trying to create named volumes that can be reused across multiple services (without relying on volumes_from due to "[PersistentVolumeClaim is not bound](http://stackoverflow.com/questions/41738374/kubernestes-persistentvolumeclaim-is-not-bound)"), kompose is unable to parse docker-compose.yml version 3 format. 

See: https://docs.docker.com/compose/compose-file/#/volume-configuration-reference

## How To Recreate
1. Create file:`touch docker-compose.yml`
1. Copy/paste:

    ```    
    version: "3"
    services:
      db:
        image: db
        volumes:
          - data-volume:/var/lib/db
      backup:
        image: backup-service
        volumes:
          - data-volume:/var/lib/backup/data

      volumes:
        data-volume:
    ```
1. Run: `kompose up -f docker-compose.yml`

## Actual Result
```
ERRO Could not parse config for project test : yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `3` into config.RawService
FATA Failed to load compose file: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `3` into config.RawService
```
## Expected Result
docker-compose.yml should successfully be converted and deployed.
