### ISSUE TITLE
underscores get propagated into invalid names

### ISSUE THREAD

**Issue by idcrook** [kubernetes-incubator/kompose#420]
searched for dupes, and found none.

docker compose file has name like: `phant_server:` in yaml, which contain embedded underscores. `kompose` does not normalize the name, resulting in invalid names being used.

#### pvc

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: phant_server-claim0
...
```

yields error

```
The PersistentVolume "phant_server-persistent-volume" is invalid: metadata.name: Invalid value: "phant_server-persistent-volume": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
```

#### deployment 

```
The Deployment "phant_server" is invalid:
* metadata.name: Invalid value: "phant_server": must match the regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* (e.g. 'example.com')
```

## possible normalization suggestions

phant_server -> phant.server
phant_server -> phant-server
phant_server -> phantserver
