### ISSUE TITLE
Support for: tmpfs

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#436]
No error / warning when using this key.

**Comment by procrypt** [comment]
@cdrage Taking this up.

**Comment by kadel** [comment]
There is actually euivalent in Kubernetes.
Its EmptyDir volume that has  `medium: "memory"`

https://kubernetes.io/docs/user-guide/volumes/#emptydir

**Comment by kadel** [comment]
My proposal is to convert `tmpfs` to empty dir volume.

for docker-compose.yml like this:
```yaml
version: "2"

services:
    foo:
        image: busybox
        command: ["sh","-c", "mount | grep /foo; sleep 3200"]
        tmpfs: 
           - /foo
```

kompose should generate objects that have PodSpec like this:
```yaml
      metadata:
        labels:
          service: foo
      spec:
        containers:
        - args:
          - sh
          - -c
          - mount | grep /foo; sleep 3200
          image: busybox
          name: foo
          volumeMounts:
          - mountPath: /foo
            name: foo-claim0
        restartPolicy: Always
        volumes:
        - name: foo-claim0
          emptyDir:
              - medium: "Memory"
```

`volumeMounts` and `volumes` are important parts.
