### ISSUE TITLE
Error with unsupported keys not showing up in warnings

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#456]
Seems that nothing warns in regards to any of the unsupported keys from `compose.go`, with the exception of "networks".

This code:
```
  var unsupportedKey = map[string]bool{                                                                                                 
    "CgroupParent":  false,                                                                                                             
    "Devices":       false,                                                                                                             
    "DependsOn":     false,                                                                                                             
    "DNS":           false,                                                                                                             
    "DNSSearch":     false,                                                                                                             
    "DomainName":    false,                                                                                                             
    "EnvFile":       false,                                                                                                             
    "Extends":       false,                                                                                                             
    "ExternalLinks": false,                                                                                                             
    "ExtraHosts":    false,                                                                                                             
    "Hostname":      false,                                                                                                             
    "Ipc":           false,                                                                                                             
    "Logging":       false,                                                                                                             
    "MacAddress":    false,                                                                                                             
    "MemSwapLimit":  false,                                                                                                             
    "NetworkMode":   false,                                                                                                             
    "Pid":           false,                                                                                                             
    "SecurityOpt":   false,                                                                                                             
    "ShmSize":       false,                                                                                                             
    "StopSignal":    false,                                                                                                             
    "VolumeDriver":  false,                                                                                                             
    "Uts":           false,                                                                                                             
    "ReadOnly":      false,                                                                                                             
    "Ulimits":       false,                                                                                                             
    "Dockerfile":    false,                                                                                                             
    "Net":           false,                                                                                                             
    "Networks":      false, // there are special checks for Network in checkUnsupportedKey function                                     
  }   
```

**Comment by cdrage** [comment]
For example, running:
```
version: "2"                                                                                                                            
                                                                                                                                        
services:                                                                                                                               
    redis:                                                                                                                              
      image: redis:3.0                                                                                                                  
      build:                                                                                                                            
        context: .                                                                                                                      
        dockerfile: foobar                                                                                                              
                                                                                                                                        
dns: 8.8.8.8                                                                                                                            
                                                                                                                                        
hostname: foobar   
```

Only produces an error from `build` being passed in. That's it.
