### ISSUE TITLE
Bug: Adding `networks:` to docker-compose.yaml file results in a runtime error

### ISSUE THREAD

**Issue by peterpme** [kubernetes-incubator/kompose#474]
`kompose version 0.3.0 (135165b3)`
`go version go1.8 darwin/amd64`

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x21eda6c]

goroutine 1 [running]:
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).handleNetworkConfig(0xc42031c0e0)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:281 +0x19c
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).load(0xc42031c0e0, 0x7fff5fbff5bb, 0x1a, 0xc42041c400, 0x69a, 0x89a, 0xc4200aa990, 0xc4204c9410)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:234 +0x490
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc42031c0e0, 0x0, 0x0)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:112 +0x162
github.com/kubernetes-incubator/kompose/pkg/loader/compose.(*Compose).LoadFile(0x365d9b0, 0xc420293480, 0x1, 0x1, 0xc4200aa8d0, 0x0, 0x10)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/pkg/loader/compose/compose.go:304 +0x10f
github.com/kubernetes-incubator/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc420293480, 0x1, 0x1, ...)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/pkg/app/app.go:214 +0x145
github.com/kubernetes-incubator/kompose/cmd.glob..func3(0x362fb00, 0xc420284fc0, 0x0, 0x2)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/cmd/convert.go:85 +0x4f
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x362fb00, 0xc420284e20, 0x2, 0x2, 0x362fb00, 0xc420284e20)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:650 +0x231
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x362ff40, 0xc42006e058, 0x0, 0xc4204c9f48)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:737 +0x339
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x362ff40, 0x1, 0x1)
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:695 +0x2b
github.com/kubernetes-incubator/kompose/cmd.Execute()
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/cmd/root.go:92 +0x31
main.main()
	/home/tomas/dev/go/src/github.com/kubernetes-incubator/kompose/main.go:22 +0x20
```

**Comment by cdrage** [comment]
Uh oh, that doesn't look right. what commands did you use / docker-compose file to get this error? @peterpme

**Comment by peterpme** [comment]
Hey @cdrage thanks for the quick response!

I ran `kompose -f docker-compose-staging.yml convert`

**Comment by surajssd** [comment]
this seems to be coming from libcompose, and would like more info on this about how does the docker-compose file looks like?

@peterpme do you mind sharing docker-compose file?

**Comment by peterpme** [comment]
@surajssd thanks for the quick response! Absolutely, if you could help me get this onto GCloud / Kubernetes I'd be very happy :)

It's an nginx reverse proxy running.

- cms `(/|blog|about-us|contact-us)`
- api `/api`
- search `/search`

```yaml
version: '2'

services:
  nginx:
    image: peterpme/nginx
    container_name: nginx
    networks:
      - peterpme-infra
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTS=www.peterp.me
      - EMAIL=peter@peterp.me
    volumes:
      - /etc/ssl/dhparam:/etc/ssl/dhparam
      - /srv/letsencrypt:/etc/letsencrypt
  cms:
    image: peterpme/cms
    container_name: cms
    environment:
      - NPM_TOKEN
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=
      - CLOUDINARY_URL=
      - COOKIE_SECRET=
      - NEW_RELIC_ENABLED=false
    networks:
      - peterpme-infra
  search:
    image: peterpme/search
    container_name: search
    environment:
      - NPM_TOKEN
      - NODE_ENV=production
      - APP_ENV=
      - PORT=5000
      - GOOGLE_PLACES_API_KEY=
      - NEW_RELIC_ENABLED=false
    networks:
      - peterpme-infra
  api:
    image: peterpme/api-next
    container_name: api
    environment:
      - NPM_TOKEN
      - NODE_ENV=production
      - DB_CONNECTION_STRING=
      - MAILCHIMP_API_KEY=
      - NEW_RELIC_ENABLED=false
    networks:
      - peterpme-infra

networks:
  peterpme-infra:
```

Thank you!

**Comment by cdrage** [comment]
Hey @peterpme 

It's 
```
networks:
  peterpme-infra:
```

That's somehow screwing it up, just remove those two lines and it'll convert fine. I'll open up another issue for this, these panics shouldn't be happening.

Thanks for opening up this issue and let us know if there is anything we can do to help!

**Comment by peterpme** [comment]
Hey @cdrage thanks! Will there be any implications on my end if I remove networks? Will the containers still be able to communicate with nginx?

**Comment by cdrage** [comment]
@peterpme Since Kubernetes is a flat-design in terms of network (there's no segregation of networks) any container created will be able to communicate to the other one.

The objective is to get you _started_ with Kubernetes. Since your docker-compose file is quite complex ,it may take some modifications to get it running (the first being persistent volumes would need to be created!)

**Comment by cdrage** [comment]
Hey @peterme, I'm going to leave this issue open and simply rename the title :) Better to keep the context in here rather than another issue.

**Comment by surajnarwade** [comment]
@surajssd  @peterpme , kompose doesn't support `networks` key yet.
for [reference](http://kompose.io/user-guide/)

**Comment by cdrage** [comment]
@surajnarwade Yes. The problem here is that this panics, so some investigation is required. I have a feeling it's because it's trying to parse:
```
networks:
  peterpme-infra:
```

and it's coming up as incorrect yaml.

**Comment by surajnarwade** [comment]
@cdrage :+1:

**Comment by surajnarwade** [comment]
@cdrage @peterpme  , I tried out above example and checked with https://docs.docker.com/compose/networking/ and its working following cases:

as `peterpme-infra` is present in all services, assuming that it's default network

```
networks:
     default:
             name: peterpme-infra
```

or if it is pre existing network:

```
networks:
     default:
         external:
             name: peterpme-infra
```

or if its not a default network, then mention network driver as below:

```
networks:
    peterpme-infra:
            driver: custom-driver
```

**Comment by kadel** [comment]
It looks like this is bug in libcompose.

```
version: '2' 
services:
  foo:
    image: busybox
    networks:
        - foo
networks:
    foo:
```
works with docker-compose:
```
▶ docker-compose up     
Creating kompose_foo_1
Attaching to kompose_foo_1
kompose_foo_1 exited with code 0
```

but fails with libcompose:
```
▶ libcompose-cli_linux-amd64 up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4d8738]

goroutine 1 [running]:
panic(0x868ac0, 0xc420010110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/libcompose/vendor/github.com/urfave/cli.HandleAction.func1(0xc420181cc8)
	/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0x868ac0, 0xc420010110)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/docker/libcompose/project.(*Project).handleNetworkConfig(0xc420082620)
	/go/src/github.com/docker/libcompose/project/project.go:281 +0x1a8
github.com/docker/libcompose/project.(*Project).load(0xc420082620, 0x8f035e, 0x12, 0xc42028d400, 0x61, 0x261, 0xc420181620, 0x410c78)
	/go/src/github.com/docker/libcompose/project/project.go:234 +0x38f
github.com/docker/libcompose/project.(*Project).Parse(0xc420082620, 0xb18e40, 0xc4202f2200)
	/go/src/github.com/docker/libcompose/project/project.go:112 +0x15a
github.com/docker/libcompose/docker.NewProject(0xc4200c2870, 0x0, 0x0, 0x0, 0x18, 0xc420181810)
	/go/src/github.com/docker/libcompose/docker/project.go:58 +0x106
github.com/docker/libcompose/cli/docker/app.(*ProjectFactory).Create(0xb66c60, 0xc4202b6500, 0x0, 0x8, 0x8, 0xc4202c4b80)
	/go/src/github.com/docker/libcompose/cli/docker/app/factory.go:20 +0xae
github.com/docker/libcompose/cli/app.WithProject.func1(0xc4202b6500, 0x0, 0x0)
	/go/src/github.com/docker/libcompose/cli/app/app.go:45 +0x4e
reflect.Value.call(0x84d260, 0xc4202c4220, 0x13, 0x8e9d90, 0x4, 0xc420181c68, 0x1, 0x1, 0x4702f8, 0x8dbe60, ...)
	/usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x84d260, 0xc4202c4220, 0x13, 0xc420181c68, 0x1, 0x1, 0x0, 0x140, 0x140)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/docker/libcompose/vendor/github.com/urfave/cli.HandleAction(0x84d260, 0xc4202c4220, 0xc4202b6500, 0x0, 0x0)
	/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/docker/libcompose/vendor/github.com/urfave/cli.Command.Run(0x8e9974, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8f1b92, 0x15, 0x0, ...)
	/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/command.go:186 +0xc26
github.com/docker/libcompose/vendor/github.com/urfave/cli.(*App).Run(0xc4202a4180, 0xc42000a3c0, 0x2, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.main()
	/go/src/github.com/docker/libcompose/cli/main/main.go:75 +0x16d4
```
