### ISSUE TITLE
kompose.service.type label not working as expected

### ISSUE THREAD

**Issue by Minx-SigEp** [kubernetes-incubator/kompose#522]
According to the documentation ( [User Guide - labels](https://github.com/kubernetes-incubator/kompose/blob/master/docs/user-guide.md#labels) ) I should be able to specify the label kompose.service.type: NodePort in docker-compose.yml. However it is not behaving as expected. My understanding is the services should be configured as described here https://kubernetes.io/docs/user-guide/services/#type-nodeport

docker-compose.yml

    version: "2"
    services:
      webapiapplication:
        image: webapiapplication
        labels:
          kompose.service.type: NodePort

Powershell command and output

    PS C:\agents\windows_01\_work\1\a> kompose -f .\docker-compose.yml convert
    INFO[0000] file "webapiapplication-service.yaml" created
    INFO[0000] file "webapiapplication-deployment.yaml" created

webapiapplication-service.yaml

    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.service.type: NodePort
      creationTimestamp: null
      labels:
        service: webapiapplication
      name: webapiapplication
    spec:
      clusterIP: None
      ports:
      - name: headless
        port: 55555
        targetPort: 0
      selector:
        service: webapiapplication
    status:
      loadBalancer: {}

webapiapplication-deployment.yaml

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.service.type: NodePort
      creationTimestamp: null
      name: webapiapplication
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            service: webapiapplication
        spec:
          containers:
          - image: webapiapplication
            name: webapiapplication
            resources: {}
          restartPolicy: Always
    status: {}

**Comment by Minx-SigEp** [comment]
Found the below article which shows the use of the labels in a slightly different manner and this as well does not work. 

http://sysadvent.blogspot.com/2016/12/day-11-going-from-local-docker-compose.html

docker-compose.yml

    version: "2"
    services:
      webapiapplication:
        image: webapiapplication
        labels:
         - "com.example.description=MyDescription"
         - "kompose.service.type=nodeport"

**Comment by cdrage** [comment]
@Minx-SigEp 

You're missing a port!

Since there's no port being added, it's being created as a headless service.

@kadel I think we should still have ClusterIP / LoadBalancer / Whatever-they-choose added as a `type:` regardless if they have specified a port or not, do you agree?

**Comment by kadel** [comment]
> @kadel I think we should still have ClusterIP / LoadBalancer / Whatever-they-choose added as a type: regardless if they have specified a port or not, do you agree?

We can try that. But I'm afraid that it won't work as expected. 
If there there is a docker-compose service without port, create kubernetes [headless service](https://kubernetes.io/docs/user-guide/services/#headless-services), I'm afraid that it doesn't make sense or is even possible to create headless service that is  NodePort or LoadBalancer, in all those cases you need to know port number.

Haven't done any research around that, there might be some workaround that I don't know about.

**Comment by cdrage** [comment]
@kadel So best thing to do would be to warn instead.

**Comment by kadel** [comment]
@cdrage Yes, I would consider even failing. It doesn't really make sense to use LoadBalancer or NodePort without specifying port.

**Comment by procrypt** [comment]
@cdrage I tried it out using the with the docker-compose file

`docker-compose.yml`
```yaml
version: "2"
services:
  webapiapplication:
    image: centos/httpd
    labels:
      kompose.service.type: NodePort
```

`webapiapplication-service.yaml`
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.service.type: NodePort
  creationTimestamp: null
  labels:
    io.kompose.service: webapiapplication
  name: webapiapplication
spec:
  clusterIP: None
  type: NodePort
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: webapiapplication
status:
  loadBalancer: {}
```

`webapiapplication-deployment.yaml`
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.service.type: NodePort
  creationTimestamp: null
  name: webapiapplication
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webapiapplication
    spec:
      containers:
      - image: centos/httpd
        name: webapiapplication
        resources: {}
      restartPolicy: Always
status: {}
```
The application has been deployed but it is not reachable from outside the container

```bash
$ kubectl describe service webapiapplication
Name:                   webapiapplication
Namespace:              default
Labels:                 io.kompose.service=webapiapplication
Selector:               io.kompose.service=webapiapplication
Type:                   NodePort
IP:                     None
Port:                   headless        55555/TCP
NodePort:               headless        30289/TCP
Endpoints:              172.17.0.3:55555
Session Affinity:       None
No events.
```

```bash
$ curl `minikube ip`:30289
curl: (7) Failed to connect to 192.168.99.100 port 30289: Connection refused
```

Its not reachable even inside the container

```bash
$ kubectl logs webapiapplication-3252267673-kjdzt 
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message
```
```bash
$ kubectl exec -it webapiapplication-3252267673-kjdzt bash
[root@webapiapplication-3252267673-kjdzt /]# curl 172.17.0.3:55555
curl: (7) Failed connect to 172.17.0.3:55555; Connection refused
```
