### ISSUE TITLE
Support for cap_add,cap_drop

### ISSUE THREAD

**Issue by gitlawr** [kubernetes-incubator/kompose#575]
Currently these keys are marked as unsupported and kompose generates WARNINGs when they are used. But I think there is equivalent in Kubernetes.
see:
https://kubernetes.io/docs/concepts/policy/container-capabilities/
My proposal is to convert `cap_add/cap_drop` to `Pod.Spec.Container.SecurityContext.capabilities.add/drop`
For example with such a docker-compose.yml

```
version: "2"

services:
    hello-world:
        image: alpine:3.4
        command: ["/bin/echo", "hello", "world"]
        cap_add:
          - SYS_NICE
        cap_drop:
          - KILL
```
kompose generate
```
metadata:
  labels:
    service: hello-world
spec:
  containers:
  - image: "alpine:3.4"
    command: ["/bin/echo", "hello", "world"]
    securityContext:
      capabilities:
        add:
        - SYS_NICE
        drop:
        - KILL
```
