### ISSUE TITLE
Is this a case of buildconfig contextDir being incorrectly set?

### ISSUE THREAD

**Issue by ashetty1** [kubernetes-incubator/kompose#593]
My docker-compose file:

```
version: "2"

services:
 foo:
  build:
   context: "./build"
  command: "sleep 120"

```
And when I run `kompose convert`:

```
"runPolicy": "Serial",
        "source": {
          "type": "Git",
          "git": {
            "uri": "https://github.com/kubernetes-incubator/kompose.git",
            "ref": "master"
          },
          "contextDir": "examples/buildconfig/examples/buildconfig/build"
        },
        "strategy": {
          "type": "Docker",
          "dockerStrategy": {}
```

I don't see the same behaviour with this docker-compose file:

```
version: "2"

services:
 foo:
  build: "./build"
  command: "sleep 120"
```

The contextDir is set correctly with the above docker compose file:

```
 "runPolicy": "Serial",
        "source": {
          "type": "Git",
          "git": {
            "uri": "https://github.com/kubernetes-incubator/kompose.git",
            "ref": "master"
          },
            "contextDir": "examples/buildconfig/build"
        },
        "strategy": {
          "type": "Docker",
          "dockerStrategy": {}
        }
```
Can you please confirm, @surajnarwade
