### ISSUE TITLE
image tag name absent from generated imagestream config

### ISSUE THREAD

**Issue by arcolife** [kubernetes-incubator/kompose#611]
On running `kompose up --provider openshift` the image build is completed, but the container never starts. All I see on `oc get pods` is:

```
myproject   web-1-build                     0/1       Completed           0          10m
```

On manually triggering the container through `oc rollout latest dc/web`, I get 
```
Error from server (BadRequest): cannot trigger a deployment for "web" because it contains unresolved images
```
On checking `oc edit is web` I get 
```
spec: {}
```

so then on checking `oc get is` I see:
```
web           172.30.1.1:5000/myproject/web           latest    20 minutes ago
```
But my docker compose file contains the following info:

```
<snip>
  web:
    restart: always
    build:
      context: lib/backend
      args:
        BACKEND_SERVER_PORT: $BACKEND_SERVER_PORT
    env_file: .env
    image: sarjitsu:backend
    ports:
    - "${BACKEND_PORT_MAPPING}:${BACKEND_SERVER_PORT}"
    depends_on:
...
</snip>
```

The `:backend` tag should've been applied to the image, but that field `spec` in `is` is empty. Hence we see `..because it contains unresolved images` and no container launches.

We could workaround this through `oc edit dc web` ..by changing `name: web:backend` to `name: web:latest`  like this:

```
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - web
      from:
        kind: ImageStreamTag
        name: web:latest
        namespace: myproject
      lastTriggeredImage: 172.30.1.1:5000/myproject/web@sha256:a906e1715d23ac84f431c565cd32ee148b997d49bf8b5a529351f2a1c2a812e7
    type: ImageChange
```

Conclusion is, the tag `:backend` is not appearing in image stream, but is present in deployment config.

The same error could be verified by checking contents of `web-imagestream.yaml`  when generating config files `kompose convert -f docker-compose.yml  --provider openshift` ..where the `:backend` tag is absent :
```
apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec: {}
status:
  dockerImageRepository: ""
``` 

#### kompose
0.6.0 (HEAD)
(built from repo's master branch)

#### openshift
```
oc v1.5.0
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.209.68.209:8443
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
```

### Supplementary info
Docker compose config being referred to in here, is at https://github.com/arcolife/sarjitsu/blob/non-root/docker-compose.yml#L56

### Related

Not sure this should be the way it is, but a tangentially related issue is that [this image name `sarjitsu:backend`](https://github.com/arcolife/sarjitsu/blob/non-root/docker-compose.yml#L63) is not appearing anywhere in openshift's imagestreams / pod names, while It appears that way when using docker-compose:
```
sarjitsu_web_1           /docker-entrypoint.sh backend    Up      0.0.0.0:9704->80/tcp   
```

Rather, it's all based out of the service names I assign, like `web:backend`

cc/ @procrypt @surajnarwade @containscafeine
