### ISSUE TITLE
kompose.service.type issues

### ISSUE THREAD

**Issue by cdrage** [kubernetes-incubator/kompose#673]
For some odd reason, our example no longer works:
```
version: "2"                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                  
services:                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
  redis-master:                                                                                                                                                                                                                                                                   
    image: gcr.io/google_containers/redis:e2e                                                                                                                                                                                                                                     
    ports:                                                                                                                                                                                                                                                                        
      - "6379"                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                  
  redis-slave:                                                                                                                                                                                                                                                                    
    image: gcr.io/google_samples/gb-redisslave:v1                                                                                                                                                                                                                                 
    ports:                                                                                                                                                                                                                                                                        
      - "6379"                                                                                                                                                                                                                                                                    
    environment:                                                                                                                                                                                                                                                                  
      - GET_HOSTS_FROM=dns                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                  
  frontend:                                                                                                                                                                                                                                                                       
    image: gcr.io/google-samples/gb-frontend:v4                                                                                                                                                                                                                                   
    ports:                                                                                                                                                                                                                                                                        
      - "80:80"                                                                                                                                                                                                                                                                   
    environment:                                                                                                                                                                                                                                                                  
      - GET_HOSTS_FROM=dns                                                                                                                                                                                                                                                        
    labels:                                                                                                                                                                                                                                                                       
      kompose.service.type: LoadBalancer  
```

```
▶ kompose convert -v
DEBU Checking validation of provider %skubernetes 
DEBU 'docker-compose.yml' not found: stat docker-compose.yml: no such file or directory 
DEBU Docker Compose version: 2                    
DEBU Opening compose files: docker-compose.yaml   
DEBU [0/1] [frontend]: Adding                     
DEBU [0/1] [redis-master]: Adding                 
DEBU [0/3] [redis-slave]: Adding                  
DEBU [0/3] [default]: EventType: 32               
DEBU [0/3] [default]: EventType: 32               
DEBU [0/3] [default]: EventType: 32               
DEBU Default network found                        
FATA kompose.service.type can't be set if service doesn't expose any ports.: LoadBalancer defined in service frontend with no ports present. Issues may occur when bringing up artifacts. 
```
