### ISSUE TITLE
Image name not given still kompose does not errors out

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#92]
Using docker-compose file that has no field for image, so this should error out, but this still works.

``` yaml
$ cat /tmp/docker-compose-no-image.yml 
version: "2"

services:
  mariadb:
    ports:
      - 3306
```

output

``` yaml
$ kompose convert --stdout -y -f /tmp/docker-compose-no-image.yml                                                                                                                       
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mariadb
  name: mariadb
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    service: mariadb
status:
  loadBalancer: {}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mariadb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mariadb
    spec:
      containers:
      - name: mariadb
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}

---
```

**Comment by runseb** [comment]
is there a way to validate the docker-compose file with lib compose ?

**Comment by ngtuna** [comment]
@runseb : `docker-compose` has this validation. `libcompose` should have. 

```console
$ cat docker-compose.yml
web:
  links:
   - redis
redis:

$ docker-compose up
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
```

**Comment by ngtuna** [comment]
Found it.
https://github.com/docker/libcompose/blob/master/config/validation.go#L263

@surajssd you will see `kompose` currently use function Parse() of `libcompose` in order to read compose file. It should then call to `validateServiceConstraints()` above.

**Comment by surajssd** [comment]
@ngtuna thanks for that pointer :-)

**Comment by surajssd** [comment]
@ngtuna now when I started working on this, looks like function [`validateServiceConstraints`](https://github.com/docker/libcompose/blob/master/config/validation.go#L263) is not exported so, we might need different way to validate the values.

**Comment by surajssd** [comment]
Also with libcompose I found this thing:

```yaml
[vagrant@fedora tmp]$ cat docker-compose.yml 
version: "2"

services:
  mariadb:
    ports:
      - 3306
```
somehow the docker-compose warning is not what I get

```bash
[vagrant@fedora tmp]$ libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
INFO[0000] [0/1] [mariadb]: Starting                    
ERRO[0000] Failed Starting mariadb : Error: No such image: tmp_mariadb 
ERRO[0000] Failed to start: mariadb : Error: No such image: tmp_mariadb 
Error: No such image: tmp_mariadb
```
Using following libcompose version

```bash
$ libcompose version
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
Version:      0.3.0-dev (HEAD)
Go version:   go1.6.3
```

**Comment by surajssd** [comment]
But for a docker-compose file of v1 like this
```yaml
[vagrant@fedora tmp]$ cat docker-compose.yml
mariadb:
  ports:
    - 3306
```

I get errors similar to docker-compose

```bash
[vagrant@fedora tmp]$ libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
ERRO[0000] Could not parse config for project tmp : Service 'mariadb' has neither an image nor a build path specified. Exactly one must be provided. 
FATA[0000] Failed to read project: Service 'mariadb' has neither an image nor a build path specified. Exactly one must be provided.
```

**Comment by surajssd** [comment]
Filed issue in libcompose https://github.com/docker/libcompose/issues/357

**Comment by sebgoa** [comment]
@surajssd @ngtuna looks like lib compose now got validation for v2 https://github.com/docker/libcompose/pull/371

We should try to close this.

**Comment by ngtuna** [comment]
Well yeah, upgrade libcompose will help solving couple of problems. 
Hey @kadel , I could help to do that while you are taking care of k8s go client.

**Comment by kadel** [comment]
@ngtuna sure, go ahead

**Comment by ngtuna** [comment]
closed via https://github.com/skippbox/kompose/pull/195

**Comment by surajssd** [comment]
@ngtuna this is issue is not fixed yet!

**Comment by surajssd** [comment]
docker-compose file
```yaml
$ cat docker-compose-no-image.yml 
version: "2"

services:
  mariadb:
    ports:
      - 3306

  etherpad:
    ports:
      - "80:9001"
```


output

```yaml
$ kompose -f docker-compose-no-image.yml convert --stdout -y
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
[SNIP]
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: mariadb
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: mariadb
      spec:
        containers:
        - name: mariadb
          ports:
          - containerPort: 3306
            protocol: TCP
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: etherpad
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          service: etherpad
      spec:
        containers:
        - name: etherpad
          ports:
          - containerPort: 9001
            protocol: TCP
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}
```
