### ISSUE TITLE
Support BuildConfigs for openshift provider

### ISSUE THREAD

**Issue by surajssd** [kubernetes-incubator/kompose#96]
When the provider is selected as `openshift` and if docker-compose file has `build` directive then create a `buildconfig` out of it, along with `deploymentconfig` and `service`

**Comment by rtnpro** [comment]
I want to work on this issue.

**Comment by surajssd** [comment]
@rtnpro I am thinking of handling builds in multiple ways:

- When user has git repo create a [buildconfig](https://docs.openshift.org/latest/dev_guide/builds.html) and [imagestream](https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#image-streams) using that git directory info
- But a user might also wanna do a local build, so he wants build to happen using dockerfile, so i am working on a parallel build story which will build docker images using [imagebuilder](https://github.com/openshift/imagebuilder/) and that image names can be added to [deploymentconfig](https://docs.openshift.com/enterprise/3.0/dev_guide/deployments.html) and made to use those images rather than pulling it from docker hub, so I am planning to add a flag to kompose cli which does this, but this assumes that user will be running a single node cluster using minikube or minishift or CDK and user will have to export some variables that enables us to talk to remote docker daemon.

**Comment by kadel** [comment]
> But a user might also wanna do a local build, so he wants build to happen using dockerfile, so i am working on a parallel build story which will build docker images using imagebuilder and that image names can be added to deploymentconfig and made to use those images rather than pulling it from docker hub, so I am planning to add a flag to kompose cli which does this, but this assumes that user will be running a single node cluster using minikube or minishift or CDK and user will have to export some variables that enables us to talk to remote docker daemon.

To  be honest, I don't like assumption that user is using single node cluster. 
And even than I don't think that majority of users are going to run kompose on same machine where their single node cluster is running. For example if I'm using minikube I'm never going to run kompose in minikube VM.

**Comment by surajssd** [comment]
@kadel 
- We assume that user will run a single node only when that flag is provided
- We can do builds on that cluster machine, only if the environment variables are exported, using imagebuilder. Remote builds are possible once we export those environments.
- User will be running kompose on his machine not on the cluster machine.

**Comment by kadel** [comment]
My issue with this is that it is quite limiting :-( This requires that you have single node cluster, and that you have remote access to that docker daemon. 

Wouldn't be better to build that image locally and that push it to OpenShift's registry? We have done similar thing in [OpenShift2Nulecule](https://github.com/projectatomic/openshift2nulecule). This will also work with clusters. OpenShift has already internal registry and for Kubernetes  we can use its registry addon as mentioned in https://github.com/skippbox/kompose/issues/97#issuecomment-239018220

**Comment by surajssd** [comment]
So going ahead we right now only implement what OpenShift by default provides, which is detect the source code's git remote and create buildConfigs with that info in buildconfig artifact.

Further we still have to work on doing local builds without having to rely on remote git repo.

**Comment by kadel** [comment]
> So going ahead we right now only implement what OpenShift by default provides, which is detect the source code's git remote and create buildConfigs with that info in buildconfig artifact.

Just to explain this more deeply how this is example who will work:
I have cloned repo github.com/foo/bar on my local machine.
In this repo is docker-compose.yml that looks like this:
```yaml
versoin: 2
services:
   foo:
      build: ./
```
When you run kompose on this file, kompose will try to detect remote of this git and use it as source for build.
generated BuildConfig will probably look something like this:
```yml
  apiVersion: v1
  kind: BuildConfig
  metadata:
    name: foo
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: foo:latest
    source:
      type: Git
      git:
        ref: master
        uri: http://github.com/foo/bar
      contextDir: ./
    strategy:
      dockerStrategy:
        type: Docker
        from:
          kind: ImageStreamTag
          name: foo:from
    triggers:
      - type: ConfigChange
      - type: ImageChange
```

**This means that build is not from local directory but from remote git repository. 
Only what is committed and pushed to remote is build.**
